HW06 is completed
AndreiGoStorm/go-home-work pull request #6
Opened 2024-09-12 03:58 UTC by AndreiGoStorm

## Домашнее задание №6 «Пайплайн»
Необходимо реализовать функцию для запуска конкуррентного пайплайна, состоящего из стейджей.

Стейдж - функция, принимающая канал на чтение и отдающая канал на чтение, внутри в горутине берущая данные из входного канала, выполняющая полезную работу и отдающая результат в выходной канал:
```golang
func Stage(in <-chan interface{}) (out <-chan interface{}) {
    out = make(chan interface{})
    go func() { /* Some work */ }()
    return out
}
```

Особенность пайплайна в том, что обработка последующего элемента входных данных должна
происходить **без ожидания завершения всего пайплайна** для текущего элемента.

Т.е. пайплан из 4 функций по 100 мс каждая для 5 входных элементов **должен выполняться
гораздо быстрее**, чем за 2 секунды (4 * 100 мс * 5).

Также **должна быть реализована возможность остановить пайплайн** через
дополнительный сигнальный канал (`done`/`terminate`/etc.).

При необходимости можно выделять дополнительные функции.

**Нельзя менять сигнатуры исходных функций.**

Для большего понимания см. тесты.

### Критерии оценки
- CI-пайплайн зелёный - 5 баллов
- Добавлены новые юнит-тесты - до 2 баллов
- Проходит тест TestAllStageStop - 2 балла
- Понятность и чистота кода - до 1 баллов

#### Зачёт от 7 баллов

### Подсказки
- https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables
- `go test -v -race -count=100 .`

2024-09-12 06:59 UTC, vladislavmass requested changes

2024-09-12 06:59 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				return channels[len(channels)-1]
Возвращать не то что надо это крайне сомнительная идея всегда. Например запускался пайплайн из 10 элементо и на запуске 6 стейджа прилетел donе и мы по этой  логике вернули канал в который пишет 5 стейдж. Предположим стейдж уже успел отработать и 5 канал готов записать значение. И получается что наш вызывающий код получит невалидное значение, но работать с ним будет как с валидным

2024-09-12 06:59 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +		case _, ok := <-done:
Этот селект по сути лишний. так как весь этот код запуска стейджей отработает очень быстро и шанс что во время его работы прилетит done крайне мал. Ведь по сути, все что делается в этом цикле это создает каналы и дается задание планировщику запустить горутины

2024-09-12 06:59 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +	channels := make([]Out, 0, len(stages))
Поясните для чего нужен этот слайс. По логике кода нам всегда хватает последнего

2024-09-12 06:59 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +		for v := range in {
Логика этого метода примерно такова. Мы ждем пока горутина нам вернет результат работы, и потом идем играть в повезет не повезет. Если повезет то мы выйдем по done, если нет то перешлем  результат работы  в следующую горутину и пусть она работает. Звучит как то не по заданию. Понятно что мы не можем заверишть этот метод, пока прошлая горутина не до работает. Но это не значит что мы не должны во время ожидания обработать Donе и уведомить следующую горутину о том, от нас инфы не будет.

2024-09-12 06:59 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				channels = append(channels, stage(takeValue(in, done)))
Странная логика ставить горутину пересылки перед стейджем, а не после.

2024-09-12 14:06 UTC, AndreiGoStorm commented on hw06_pipeline_execution/pipeline.go
> +	channels := make([]Out, 0, len(stages))
убрал его

2024-09-14 17:55 UTC, vladislavmass approved these changes

2024-09-14 18:19 UTC, merged